repos:
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        types: [python]
        entry: pdm run black .
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff
        name: ruff
        stages: [commit]
        types: [python]
        entry: pdm run ruff check .
        language: system
        pass_filenames: false
        always_run: true
        fail_fast: true
        always_run: true
      - id: isort
        name: isort
        stages: [commit]
        types: [python]
        entry: pdm run isort . --profile black
        language: system
        pass_filenames: false
        always_run: true
        fail_fast: true
      - id: pytest
        name: pytest
        stages: [commit]
        types: [python]
        entry: pdm run pytest
        language: system
        pass_filenames: false
        always_run: true
        fail_fast: true
